map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom

two_d_mode: true
publish_tf: true
frequency: 50

odom0: /odom
odom0_config: [true, true, false,
               false, false, false,
               true, true, false,
               false, false, false,
               false, false, false]
odom0_differential: true
odom0_queue_size: 10

imu0: /mobile_base/sensors/imu_data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

#dynamic_process_noise_covariance: true
